"""
Windows API call → behavioral category mapping.

Each of the ~271 API calls in the Mal-API-2019 vocabulary is assigned to one
of 8 behavioral categories.  The mapping is used to compute per-sample
category ratio features for XGBoost.

Categories:
    filesystem   — File creation, deletion, read/write, attributes, directories
    registry     — Registry key/value create, read, write, delete, enumerate
    network      — Sockets, DNS, HTTP, internet handles, send/recv
    process      — Process/thread creation, injection, memory read/write, snapshots
    memory       — Virtual memory allocation, protection, mapping, sections
    synchronization — Mutexes, delays, jobs, services, hooks
    cryptography — Crypto API calls (encrypt, decrypt, hash, key management)
    other        — System info, UI, COM, debugging, error handling, misc
"""

from typing import Dict

# Category name constants
FILESYSTEM = "filesystem"
REGISTRY = "registry"
NETWORK = "network"
PROCESS = "process"
MEMORY = "memory"
SYNCHRONIZATION = "synchronization"
CRYPTOGRAPHY = "cryptography"
OTHER = "other"

CATEGORIES = [
    FILESYSTEM,
    REGISTRY,
    NETWORK,
    PROCESS,
    MEMORY,
    SYNCHRONIZATION,
    CRYPTOGRAPHY,
    OTHER,
]

# ── Mapping ────────────────────────────────────────────────────────────────

API_CATEGORY_MAP: Dict[str, str] = {
    # ── Filesystem ─────────────────────────────────────────────────────
    "copyfilea": FILESYSTEM,
    "copyfileexw": FILESYSTEM,
    "copyfilew": FILESYSTEM,
    "createdirectoryexw": FILESYSTEM,
    "createdirectoryw": FILESYSTEM,
    "deletefilew": FILESYSTEM,
    "deleteurlcacheentrya": FILESYSTEM,
    "deleteurlcacheentryw": FILESYSTEM,
    "findfirstfileexa": FILESYSTEM,
    "findfirstfileexw": FILESYSTEM,
    "getdiskfreespaceexw": FILESYSTEM,
    "getdiskfreespacew": FILESYSTEM,
    "getfileattributesexw": FILESYSTEM,
    "getfileattributesw": FILESYSTEM,
    "getfileinformationbyhandle": FILESYSTEM,
    "getfileinformationbyhandleex": FILESYSTEM,
    "getfilesize": FILESYSTEM,
    "getfilesizeex": FILESYSTEM,
    "getfiletype": FILESYSTEM,
    "getfileversioninfosizew": FILESYSTEM,
    "getfileversioninfow": FILESYSTEM,
    "getshortpathnamew": FILESYSTEM,
    "gettemppathw": FILESYSTEM,
    "getvolumenameforvolumemountpointw": FILESYSTEM,
    "getvolumepathnamesforvolumenamew": FILESYSTEM,
    "getvolumepathnamew": FILESYSTEM,
    "movefilewithprogressw": FILESYSTEM,
    "ntcreatefile": FILESYSTEM,
    "ntdeletefile": FILESYSTEM,
    "ntopenfile": FILESYSTEM,
    "ntqueryattributesfile": FILESYSTEM,
    "ntquerydirectoryfile": FILESYSTEM,
    "ntqueryinformationfile": FILESYSTEM,
    "ntreadfile": FILESYSTEM,
    "ntsetinformationfile": FILESYSTEM,
    "ntwritefile": FILESYSTEM,
    "readcabinetstate": FILESYSTEM,
    "removedirectorya": FILESYSTEM,
    "removedirectoryw": FILESYSTEM,
    "searchpathw": FILESYSTEM,
    "setendoffile": FILESYSTEM,
    "setfileattributesw": FILESYSTEM,
    "setfileinformationbyhandle": FILESYSTEM,
    "setfilepointer": FILESYSTEM,
    "setfilepointerex": FILESYSTEM,
    "setfiletime": FILESYSTEM,

    # ── Registry ───────────────────────────────────────────────────────
    "regclosekey": REGISTRY,
    "regcreatekeyexa": REGISTRY,
    "regcreatekeyexw": REGISTRY,
    "regdeletekeya": REGISTRY,
    "regdeletekeyw": REGISTRY,
    "regdeletevaluea": REGISTRY,
    "regdeletevaluew": REGISTRY,
    "regenumkeyexa": REGISTRY,
    "regenumkeyexw": REGISTRY,
    "regenumkeyw": REGISTRY,
    "regenumvaluea": REGISTRY,
    "regenumvaluew": REGISTRY,
    "regopenkeyexa": REGISTRY,
    "regopenkeyexw": REGISTRY,
    "regqueryinfokeya": REGISTRY,
    "regqueryinfokeyw": REGISTRY,
    "regqueryvalueexa": REGISTRY,
    "regqueryvalueexw": REGISTRY,
    "regsetvalueexa": REGISTRY,
    "regsetvalueexw": REGISTRY,
    "ntcreatekey": REGISTRY,
    "ntdeletekey": REGISTRY,
    "ntdeletevaluekey": REGISTRY,
    "ntenumeratekey": REGISTRY,
    "ntenumeratevaluekey": REGISTRY,
    "ntopenkey": REGISTRY,
    "ntopenkeyex": REGISTRY,
    "ntquerykey": REGISTRY,
    "ntqueryvaluekey": REGISTRY,
    "ntsetvaluekey": REGISTRY,

    # ── Network ────────────────────────────────────────────────────────
    "accept": NETWORK,
    "bind": NETWORK,
    "closesocket": NETWORK,
    "connect": NETWORK,
    "dnsquery_a": NETWORK,
    "getadaptersaddresses": NETWORK,
    "getadaptersinfo": NETWORK,
    "getaddrinfo": NETWORK,
    "getaddrinfow": NETWORK,
    "getbestinterfaceex": NETWORK,
    "gethostbyname": NETWORK,
    "getsockname": NETWORK,
    "httpopenrequesta": NETWORK,
    "httpopenrequestw": NETWORK,
    "httpqueryinfoa": NETWORK,
    "httpsendrequesta": NETWORK,
    "httpsendrequestw": NETWORK,
    "internetclosehandle": NETWORK,
    "internetconnecta": NETWORK,
    "internetconnectw": NETWORK,
    "internetcrackurla": NETWORK,
    "internetcrackurlw": NETWORK,
    "internetgetconnectedstate": NETWORK,
    "internetgetconnectedstateexa": NETWORK,
    "internetopena": NETWORK,
    "internetopenurla": NETWORK,
    "internetopenurlw": NETWORK,
    "internetopenw": NETWORK,
    "internetqueryoptiona": NETWORK,
    "internetreadfile": NETWORK,
    "internetsetoptiona": NETWORK,
    "internetsetstatuscallback": NETWORK,
    "ioctlsocket": NETWORK,
    "listen": NETWORK,
    "obtainuseragentstring": NETWORK,
    "recv": NETWORK,
    "select": NETWORK,
    "send": NETWORK,
    "sendto": NETWORK,
    "setsockopt": NETWORK,
    "shutdown": NETWORK,
    "socket": NETWORK,
    "urldownloadtofilew": NETWORK,
    "wsarecv": NETWORK,
    "wsasocketa": NETWORK,
    "wsasocketw": NETWORK,
    "wsastartup": NETWORK,

    # ── Process (creation, injection, thread manipulation) ─────────────
    "createprocessinternalw": PROCESS,
    "createremotethread": PROCESS,
    "createremotethreadex": PROCESS,
    "createthread": PROCESS,
    "createtoolhelp32snapshot": PROCESS,
    "module32firstw": PROCESS,
    "module32nextw": PROCESS,
    "ntcreatethreadex": PROCESS,
    "ntgetcontextthread": PROCESS,
    "ntopenprocess": PROCESS,
    "ntopenthread": PROCESS,
    "ntresumethread": PROCESS,
    "ntsetcontextthread": PROCESS,
    "ntsuspendthread": PROCESS,
    "ntterminateprocess": PROCESS,
    "ntterminatethread": PROCESS,
    "process32firstw": PROCESS,
    "process32nextw": PROCESS,
    "readprocessmemory": PROCESS,
    "rtlcreateuserthread": PROCESS,
    "thread32first": PROCESS,
    "thread32next": PROCESS,
    "writeprocessmemory": PROCESS,
    "shellexecuteexw": PROCESS,

    # ── Memory (virtual memory, sections, mapping) ─────────────────────
    "ntallocatevirtualmemory": MEMORY,
    "ntfreevirtualmemory": MEMORY,
    "ntmapviewofsection": MEMORY,
    "ntcreatesection": MEMORY,
    "ntopensection": MEMORY,
    "ntprotectvirtualmemory": MEMORY,
    "ntreadvirtualmemory": MEMORY,
    "ntunmapviewofsection": MEMORY,
    "ntwritevirtualmemory": MEMORY,
    "rtlcompressbuffer": MEMORY,
    "rtldecompressbuffer": MEMORY,
    "rtldecompressfragment": MEMORY,

    # ── Synchronization (mutexes, services, hooks, delays) ─────────────
    "controlservice": SYNCHRONIZATION,
    "createjobobjectw": SYNCHRONIZATION,
    "createservicea": SYNCHRONIZATION,
    "deleteservice": SYNCHRONIZATION,
    "enumservicesstatusa": SYNCHRONIZATION,
    "ntcreatemutant": SYNCHRONIZATION,
    "ntdelayexecution": SYNCHRONIZATION,
    "ntopenmutant": SYNCHRONIZATION,
    "openscmanagera": SYNCHRONIZATION,
    "openscmanagerw": SYNCHRONIZATION,
    "openservicea": SYNCHRONIZATION,
    "openservicew": SYNCHRONIZATION,
    "registerhotkey": SYNCHRONIZATION,
    "setwindowshookexa": SYNCHRONIZATION,
    "setwindowshookexw": SYNCHRONIZATION,
    "startservicea": SYNCHRONIZATION,
    "startservicew": SYNCHRONIZATION,
    "unhookwindowshookex": SYNCHRONIZATION,

    # ── Cryptography ───────────────────────────────────────────────────
    "certopensystemstorea": CRYPTOGRAPHY,
    "cryptacquirecontexta": CRYPTOGRAPHY,
    "cryptacquirecontextw": CRYPTOGRAPHY,
    "cryptcreatehash": CRYPTOGRAPHY,
    "cryptdecodeobjectex": CRYPTOGRAPHY,
    "cryptdecrypt": CRYPTOGRAPHY,
    "cryptencrypt": CRYPTOGRAPHY,
    "cryptexportkey": CRYPTOGRAPHY,
    "cryptgenkey": CRYPTOGRAPHY,
    "crypthashdata": CRYPTOGRAPHY,
    "cryptprotectdata": CRYPTOGRAPHY,
    "cryptprotectmemory": CRYPTOGRAPHY,
    "cryptunprotectdata": CRYPTOGRAPHY,
    "cryptunprotectmemory": CRYPTOGRAPHY,

    # ── Other (system info, UI, COM, loader, debugging, misc) ──────────
    "cocreateinstance": OTHER,
    "cocreateinstanceex": OTHER,
    "cogetclassobject": OTHER,
    "coinitializeex": OTHER,
    "coinitializesecurity": OTHER,
    "couninitialize": OTHER,
    "createactctxw": OTHER,
    "deviceiocontrol": OTHER,
    "drawtextexa": OTHER,
    "drawtextexw": OTHER,
    "enumwindows": OTHER,
    "exitwindowsex": OTHER,
    "findresourcea": OTHER,
    "findresourceexa": OTHER,
    "findresourceexw": OTHER,
    "findresourcew": OTHER,
    "findwindowa": OTHER,
    "findwindowexa": OTHER,
    "findwindowexw": OTHER,
    "findwindoww": OTHER,
    "getasynckeystate": OTHER,
    "getcomputernamea": OTHER,
    "getcomputernamew": OTHER,
    "getcursorpos": OTHER,
    "getforegroundwindow": OTHER,
    "getkeyboardstate": OTHER,
    "getkeystate": OTHER,
    "getnativesysteminfo": OTHER,
    "getsystemdirectorya": OTHER,
    "getsystemdirectoryw": OTHER,
    "getsysteminfo": OTHER,
    "getsystemmetrics": OTHER,
    "getsystemtimeasfiletime": OTHER,
    "getsystemwindowsdirectorya": OTHER,
    "getsystemwindowsdirectoryw": OTHER,
    "gettimezoneinformation": OTHER,
    "getusernamea": OTHER,
    "getusernameexw": OTHER,
    "getusernamew": OTHER,
    "globalmemorystatus": OTHER,
    "globalmemorystatusex": OTHER,
    "isdebuggerpresent": OTHER,
    "iwbemservices_execmethod": OTHER,
    "iwbemservices_execquery": OTHER,
    "ldrgetdllhandle": OTHER,
    "ldrgetprocedureaddress": OTHER,
    "ldrloaddll": OTHER,
    "ldrunloaddll": OTHER,
    "loadresource": OTHER,
    "loadstringa": OTHER,
    "loadstringw": OTHER,
    "lookupaccountsidw": OTHER,
    "lookupprivilegevaluew": OTHER,
    "messageboxtimeouta": OTHER,
    "messageboxtimeoutw": OTHER,
    "netgetjoininformation": OTHER,
    "netshareenum": OTHER,
    "netusergetinfo": OTHER,
    "netusergetlocalgroups": OTHER,
    "ntclose": OTHER,
    "ntdeviceiocontrolfile": OTHER,
    "ntduplicateobject": OTHER,
    "ntopendirectoryobject": OTHER,
    "ntquerysysteminformation": OTHER,
    "oleinitialize": OTHER,
    "outputdebugstringa": OTHER,
    "rtladdvectoredcontinuehandler": OTHER,
    "rtladdvectoredexceptionhandler": OTHER,
    "sendnotifymessagew": OTHER,
    "seterrormode": OTHER,
    "setstdhandle": OTHER,
    "setunhandledexceptionfilter": OTHER,
    "shgetfolderpathw": OTHER,
    "shgetspecialfolderlocation": OTHER,
    "sizeofresource": OTHER,
    "timegettime": OTHER,
    "uuidcreate": OTHER,
    "wnetgetprovidernamew": OTHER,
    "writeconsolea": OTHER,
    "writeconsolew": OTHER,
}


def get_category(api_call: str) -> str:
    """Return the behavioral category for an API call.

    Args:
        api_call: Lowercase API call name.

    Returns:
        Category string.  Defaults to ``"other"`` if unmapped.
    """
    return API_CATEGORY_MAP.get(api_call, OTHER)
