"""
Decode map for the Olivera dataset: integer index -> Windows API call name.

The dataset encodes each API call as an integer (0-306).  This module
provides the mapping back to human-readable names so the rest of the
pipeline can work with string tokens, consistent with Mal-API and MalBehavD.

Source: decode table provided with the Olivera dataset (307 API calls).
"""

# fmt: off
_OLIVERA_API_LIST = [
    "NtOpenThread",                          # 0
    "ExitWindowsEx",                         # 1
    "FindResourceW",                         # 2
    "CryptExportKey",                        # 3
    "CreateRemoteThreadEx",                  # 4
    "MessageBoxTimeoutW",                    # 5
    "InternetCrackUrlW",                     # 6
    "StartServiceW",                         # 7
    "GetFileSize",                           # 8
    "GetVolumeNameForVolumeMountPointW",     # 9
    "GetFileInformationByHandle",            # 10
    "CryptAcquireContextW",                  # 11
    "RtlDecompressBuffer",                   # 12
    "SetWindowsHookExA",                     # 13
    "RegSetValueExW",                        # 14
    "LookupAccountSidW",                     # 15
    "SetUnhandledExceptionFilter",           # 16
    "InternetConnectA",                      # 17
    "GetComputerNameW",                      # 18
    "RegEnumValueA",                         # 19
    "NtOpenFile",                            # 20
    "NtSaveKeyEx",                           # 21
    "HttpOpenRequestA",                      # 22
    "recv",                                  # 23
    "GetFileSizeEx",                         # 24
    "LoadStringW",                           # 25
    "SetInformationJobObject",               # 26
    "WSAConnect",                            # 27
    "CryptDecrypt",                          # 28
    "GetTimeZoneInformation",                # 29
    "InternetOpenW",                         # 30
    "CoInitializeEx",                        # 31
    "CryptGenKey",                           # 32
    "GetAsyncKeyState",                      # 33
    "NtQueryInformationFile",                # 34
    "GetSystemMetrics",                      # 35
    "NtDeleteValueKey",                      # 36
    "NtOpenKeyEx",                           # 37
    "sendto",                                # 38
    "IsDebuggerPresent",                     # 39
    "RegQueryInfoKeyW",                      # 40
    "NetShareEnum",                          # 41
    "InternetOpenUrlW",                      # 42
    "WSASocketA",                            # 43
    "CopyFileExW",                           # 44
    "connect",                               # 45
    "ShellExecuteExW",                       # 46
    "SearchPathW",                           # 47
    "GetUserNameA",                          # 48
    "InternetOpenUrlA",                      # 49
    "LdrUnloadDll",                          # 50
    "EnumServicesStatusW",                   # 51
    "EnumServicesStatusA",                   # 52
    "WSASend",                               # 53
    "CopyFileW",                             # 54
    "NtDeleteFile",                          # 55
    "CreateActCtxW",                         # 56
    "timeGetTime",                           # 57
    "MessageBoxTimeoutA",                    # 58
    "CreateServiceA",                        # 59
    "FindResourceExW",                       # 60
    "WSAAccept",                             # 61
    "InternetConnectW",                      # 62
    "HttpSendRequestA",                      # 63
    "GetVolumePathNameW",                    # 64
    "RegCloseKey",                           # 65
    "InternetGetConnectedStateExW",          # 66
    "GetAdaptersInfo",                       # 67
    "shutdown",                              # 68
    "NtQueryMultipleValueKey",               # 69
    "NtQueryKey",                            # 70
    "GetSystemWindowsDirectoryW",            # 71
    "GlobalMemoryStatusEx",                  # 72
    "GetFileAttributesExW",                  # 73
    "OpenServiceW",                          # 74
    "getsockname",                           # 75
    "LoadStringA",                           # 76
    "UnhookWindowsHookEx",                   # 77
    "NtCreateUserProcess",                   # 78
    "Process32NextW",                        # 79
    "CreateThread",                          # 80
    "LoadResource",                          # 81
    "GetSystemTimeAsFileTime",               # 82
    "SetStdHandle",                          # 83
    "CoCreateInstanceEx",                    # 84
    "GetSystemDirectoryA",                   # 85
    "NtCreateMutant",                        # 86
    "RegCreateKeyExW",                       # 87
    "IWbemServices_ExecQuery",               # 88
    "NtDuplicateObject",                     # 89
    "Thread32First",                         # 90
    "OpenSCManagerW",                        # 91
    "CreateServiceW",                        # 92
    "GetFileType",                           # 93
    "MoveFileWithProgressW",                 # 94
    "NtDeviceIoControlFile",                 # 95
    "GetFileInformationByHandleEx",          # 96
    "CopyFileA",                             # 97
    "NtLoadKey",                             # 98
    "GetNativeSystemInfo",                   # 99
    "NtOpenProcess",                         # 100
    "CryptUnprotectMemory",                  # 101
    "InternetWriteFile",                     # 102
    "ReadProcessMemory",                     # 103
    "gethostbyname",                         # 104
    "WSASendTo",                             # 105
    "NtOpenSection",                         # 106
    "listen",                                # 107
    "WSAStartup",                            # 108
    "socket",                                # 109
    "OleInitialize",                         # 110
    "FindResourceA",                         # 111
    "RegOpenKeyExA",                         # 112
    "RegEnumKeyExA",                         # 113
    "NtQueryDirectoryFile",                  # 114
    "CertOpenSystemStoreW",                  # 115
    "ControlService",                        # 116
    "LdrGetProcedureAddress",                # 117
    "GlobalMemoryStatus",                    # 118
    "NtSetInformationFile",                  # 119
    "OutputDebugStringA",                    # 120
    "GetAdaptersAddresses",                  # 121
    "CoInitializeSecurity",                  # 122
    "RegQueryValueExA",                      # 123
    "NtQueryFullAttributesFile",             # 124
    "DeviceIoControl",                       # 125
    "__anomaly__",                           # 126
    "DeleteFileW",                           # 127
    "GetShortPathNameW",                     # 128
    "NtGetContextThread",                    # 129
    "GetKeyboardState",                      # 130
    "RemoveDirectoryA",                      # 131
    "InternetSetStatusCallback",             # 132
    "NtResumeThread",                        # 133
    "SetFileInformationByHandle",            # 134
    "NtCreateSection",                       # 135
    "NtQueueApcThread",                      # 136
    "accept",                                # 137
    "DecryptMessage",                        # 138
    "GetUserNameExW",                        # 139
    "SizeofResource",                        # 140
    "RegQueryValueExW",                      # 141
    "SetWindowsHookExW",                     # 142
    "HttpOpenRequestW",                      # 143
    "CreateDirectoryW",                      # 144
    "InternetOpenA",                         # 145
    "GetFileVersionInfoExW",                 # 146
    "FindWindowA",                           # 147
    "closesocket",                           # 148
    "RtlAddVectoredExceptionHandler",        # 149
    "IWbemServices_ExecMethod",              # 150
    "GetDiskFreeSpaceExW",                   # 151
    "TaskDialog",                            # 152
    "WriteConsoleW",                         # 153
    "CryptEncrypt",                          # 154
    "WSARecvFrom",                           # 155
    "NtOpenMutant",                          # 156
    "CoGetClassObject",                      # 157
    "NtQueryValueKey",                       # 158
    "NtDelayExecution",                      # 159
    "select",                                # 160
    "HttpQueryInfoA",                        # 161
    "GetVolumePathNamesForVolumeNameW",      # 162
    "RegDeleteValueW",                       # 163
    "InternetCrackUrlA",                     # 164
    "OpenServiceA",                          # 165
    "InternetSetOptionA",                    # 166
    "CreateDirectoryExW",                    # 167
    "bind",                                  # 168
    "NtShutdownSystem",                      # 169
    "DeleteUrlCacheEntryA",                  # 170
    "NtMapViewOfSection",                    # 171
    "LdrGetDllHandle",                       # 172
    "NtCreateKey",                           # 173
    "GetKeyState",                           # 174
    "CreateRemoteThread",                    # 175
    "NtEnumerateValueKey",                   # 176
    "SetFileAttributesW",                    # 177
    "NtUnmapViewOfSection",                  # 178
    "RegDeleteValueA",                       # 179
    "CreateJobObjectW",                      # 180
    "send",                                  # 181
    "NtDeleteKey",                           # 182
    "SetEndOfFile",                          # 183
    "GetUserNameExA",                        # 184
    "GetComputerNameA",                      # 185
    "URLDownloadToFileW",                    # 186
    "NtFreeVirtualMemory",                   # 187
    "recvfrom",                              # 188
    "NtUnloadDriver",                        # 189
    "NtTerminateThread",                     # 190
    "CryptUnprotectData",                    # 191
    "NtCreateThreadEx",                      # 192
    "DeleteService",                         # 193
    "GetFileAttributesW",                    # 194
    "GetFileVersionInfoSizeExW",             # 195
    "OpenSCManagerA",                        # 196
    "WriteProcessMemory",                    # 197
    "GetSystemInfo",                         # 198
    "SetFilePointer",                        # 199
    "Module32FirstW",                        # 200
    "ioctlsocket",                           # 201
    "RegEnumKeyW",                           # 202
    "RtlCompressBuffer",                     # 203
    "SendNotifyMessageW",                    # 204
    "GetAddrInfoW",                          # 205
    "CryptProtectData",                      # 206
    "Thread32Next",                          # 207
    "NtAllocateVirtualMemory",               # 208
    "RegEnumKeyExW",                         # 209
    "RegSetValueExA",                        # 210
    "DrawTextExA",                           # 211
    "CreateToolhelp32Snapshot",              # 212
    "FindWindowW",                           # 213
    "CoUninitialize",                        # 214
    "NtClose",                               # 215
    "WSARecv",                               # 216
    "CertOpenStore",                         # 217
    "InternetGetConnectedState",             # 218
    "RtlAddVectoredContinueHandler",         # 219
    "RegDeleteKeyW",                         # 220
    "SHGetSpecialFolderLocation",            # 221
    "CreateProcessInternalW",                # 222
    "NtCreateDirectoryObject",               # 223
    "EnumWindows",                           # 224
    "DrawTextExW",                           # 225
    "RegEnumValueW",                         # 226
    "SendNotifyMessageA",                    # 227
    "NtProtectVirtualMemory",                # 228
    "NetUserGetLocalGroups",                 # 229
    "GetUserNameW",                          # 230
    "WSASocketW",                            # 231
    "getaddrinfo",                           # 232
    "AssignProcessToJobObject",              # 233
    "SetFileTime",                           # 234
    "WriteConsoleA",                         # 235
    "CryptDecodeObjectEx",                   # 236
    "EncryptMessage",                        # 237
    "system",                                # 238
    "NtSetContextThread",                    # 239
    "LdrLoadDll",                            # 240
    "InternetGetConnectedStateExA",          # 241
    "RtlCreateUserThread",                   # 242
    "GetCursorPos",                          # 243
    "Module32NextW",                         # 244
    "RegCreateKeyExA",                       # 245
    "NtLoadDriver",                          # 246
    "NetUserGetInfo",                        # 247
    "SHGetFolderPathW",                      # 248
    "GetBestInterfaceEx",                    # 249
    "CertControlStore",                      # 250
    "StartServiceA",                         # 251
    "NtWriteFile",                           # 252
    "Process32FirstW",                       # 253
    "NtReadVirtualMemory",                   # 254
    "GetDiskFreeSpaceW",                     # 255
    "GetFileVersionInfoW",                   # 256
    "FindFirstFileExW",                      # 257
    "FindWindowExW",                         # 258
    "GetSystemWindowsDirectoryA",            # 259
    "RegOpenKeyExW",                         # 260
    "CoCreateInstance",                      # 261
    "NtQuerySystemInformation",              # 262
    "LookupPrivilegeValueW",                 # 263
    "NtReadFile",                            # 264
    "ReadCabinetState",                      # 265
    "GetForegroundWindow",                   # 266
    "InternetCloseHandle",                   # 267
    "FindWindowExA",                         # 268
    "ObtainUserAgentString",                 # 269
    "CryptCreateHash",                       # 270
    "GetTempPathW",                          # 271
    "CryptProtectMemory",                    # 272
    "NetGetJoinInformation",                 # 273
    "NtOpenKey",                             # 274
    "GetSystemDirectoryW",                   # 275
    "DnsQuery_A",                            # 276
    "RegQueryInfoKeyA",                      # 277
    "NtEnumerateKey",                        # 278
    "RegisterHotKey",                        # 279
    "RemoveDirectoryW",                      # 280
    "FindFirstFileExA",                      # 281
    "CertOpenSystemStoreA",                  # 282
    "NtTerminateProcess",                    # 283
    "NtSetValueKey",                         # 284
    "CryptAcquireContextA",                  # 285
    "SetErrorMode",                          # 286
    "UuidCreate",                            # 287
    "RtlRemoveVectoredExceptionHandler",     # 288
    "RegDeleteKeyA",                         # 289
    "setsockopt",                            # 290
    "FindResourceExA",                       # 291
    "NtSuspendThread",                       # 292
    "GetFileVersionInfoSizeW",               # 293
    "NtOpenDirectoryObject",                 # 294
    "InternetQueryOptionA",                  # 295
    "InternetReadFile",                      # 296
    "NtCreateFile",                          # 297
    "NtQueryAttributesFile",                 # 298
    "HttpSendRequestW",                      # 299
    "CryptHashMessage",                      # 300
    "CryptHashData",                         # 301
    "NtWriteVirtualMemory",                  # 302
    "SetFilePointerEx",                      # 303
    "CertCreateCertificateContext",          # 304
    "DeleteUrlCacheEntryW",                  # 305
    "__exception__",                         # 306
]
# fmt: on

OLIVERA_API_DECODE: dict[int, str] = {
    i: name for i, name in enumerate(_OLIVERA_API_LIST)
}
